# Generated by Django 5.0.3 on 2024-03-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanInformation',
        ),
    ]
