# Generated by Django 5.0.3 on 2024-03-09 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0002_delete_planinformation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_cctvs', models.IntegerField(default=1)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_hours', models.IntegerField(blank=True, editable=False, null=True)),
                ('period', models.CharField(choices=[('month', 'Month'), ('year', 'Year')], default='month', max_length=5)),
                ('card_choice', models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('diamond', 'Diamond')], max_length=7)),
                ('final_price', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
